### ISSUE TITLE
Problem with translations in CasaOS

### ISSUE THREAD

**Issue by AmadeusGraves** [IceWhaleTech/CasaOS-i18n#29]
The CasaOS translation is giving a lot of problems because it is so decentralised. In the i18n project, there are some translations and in the CasaOS UI project there are others. We are getting to a point where it is very difficult to translate or find all the entries.

That's why I think we should centralise translations with an internationalisation software such as 
[Tolgee](https://tolgee.io/)
[Lokalise](https://learn.lokalise.com/translation-software/?utm_source=google&utm_medium=cpc&utm_campaign=EMEA_LOK_Search_Localization_General&utm_content=140445750131-607668921797&utm_term=localization%20software&cq_src=google_ads&cq_cmp=16629418796&cq_term=localization%20software&cq_plac=&cq_net=g&cq_plt=gp)
[Poeditor](https://poeditor.com/)
[Weblate](https://weblate.org/en/)

I have also been noticing that translations done in the i18n project are not being ported to the UI project. If any of these alternatives are implemented we will have no more problems with localisation, everything will be automatic and it will be less of a burden for the developers.

**Comment by AmadeusGraves** [comment]
I think this is already necessary before the project progresses further, because the json file of the translations is getting bigger and bigger.

**Comment by Mat-DB** [comment]
Openmediavault uses Transifex for their translations, this might not be a bad option to look into as well.
I don't know much about it at the moment, I can only tell you.

**Comment by AmadeusGraves** [comment]
I close this issue because there are another in the main project and its resolved.

https://github.com/IceWhaleTech/CasaOS/issues/540
